// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcz1tUdufUobs9WCIW1qCOlgR_mcEnL9U',
    appId: '1:1031280055187:web:5125625ab7ab2684ae8e66',
    messagingSenderId: '1031280055187',
    projectId: 'green-taxi-d8a1e',
    authDomain: 'green-taxi-d8a1e.firebaseapp.com',
    storageBucket: 'green-taxi-d8a1e.appspot.com',
    measurementId: 'G-P39H3KV6GY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXvcsHy1rPrHraL-2AZ9dzQN_k3VJ45YA',
    appId: '1:1031280055187:android:56e7c4d622fcd420ae8e66',
    messagingSenderId: '1031280055187',
    projectId: 'green-taxi-d8a1e',
    storageBucket: 'green-taxi-d8a1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh5lqcTCfkEaLIya_EvNW-EoDmm1k47Mc',
    appId: '1:1031280055187:ios:8507684431139d71ae8e66',
    messagingSenderId: '1031280055187',
    projectId: 'green-taxi-d8a1e',
    storageBucket: 'green-taxi-d8a1e.appspot.com',
    iosClientId: '1031280055187-l5aup2ehv52o4fc8uaj9dhvpkfm57nq3.apps.googleusercontent.com',
    iosBundleId: 'com.example.getx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh5lqcTCfkEaLIya_EvNW-EoDmm1k47Mc',
    appId: '1:1031280055187:ios:8507684431139d71ae8e66',
    messagingSenderId: '1031280055187',
    projectId: 'green-taxi-d8a1e',
    storageBucket: 'green-taxi-d8a1e.appspot.com',
    iosClientId: '1031280055187-l5aup2ehv52o4fc8uaj9dhvpkfm57nq3.apps.googleusercontent.com',
    iosBundleId: 'com.example.getx',
  );
}
